from selenium import webdriver
from selenium.webdriver.common.by import By
import time


def get_prices():
    """
    Scrapes currency names and prices and returns them as a dictionary.
    The data on tgju.org gets updated after a couple of seconds and for this
    reason we use selenium and time.sleep() for scraping data with delay.
    """
    try:
        with webdriver.Firefox() as driver:
            driver.get('https://www.tgju.org/currency')
            time.sleep(10)
            # Prices are in tags with different classes. we add all of them to rows.
            # rows is a list generated by selenium.
            rows = driver.find_elements(By.CLASS_NAME, 'pointer')
            rows += driver.find_elements(By.CLASS_NAME, 'tr-low')
            rows += driver.find_elements(By.CLASS_NAME, 'tr-high')
            rows += driver.find_elements(By.CLASS_NAME, 'row-.tr-')
            currency_prices = {}

            for row in rows:
                name = row.find_element(By.TAG_NAME, 'th').text
                price = row.find_element(By.TAG_NAME, 'td').text
                price = price.split(',')
                price = ''.join(price)
                price = int(price)
                currency_prices[name] = price

            return currency_prices
    except Exception as e:
	    print(e)